### PR TITLE
Fix 199: Agora tracks and Firestore timings

### LINKED ISSUE #199: Cannot Join properly to my Room at the second time
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by RQ2L84Q-ROW**
Fix #199 
# Agora Track invisible -> visible
I added `await` at `client.subscribe`

# Firestore timing fix
It seems just adding `await` before `stat_firebase.init()` in `agora.js` did not fix the issue.
Instead, I modified `try{}...catch{}...finally{}` structure at `stat_firebase.js` which resolved the issue.

# One more thing...
I created custom logging function.
Use this for loggings that are not for debugging.

```javascript
export function statConsoleLog(msg) {
	console.log(`%cStat! [DEBUG]: %c${msg}`, 'color: #8f35ff', 'color: #0D0D0D');
}
```

Screen Shot 2021-09-23 at 10 50 16

Screen Shot 2021-09-23 at 10 38 26

### CODE REVIEW

**Review by yhakamay — CHANGES_REQUESTED** [review]
@RQ2L84Q-ROW It seems not working. Confirmed Google Accounts are different each. I joined a channel via "New Meeting."
image
image

**Comment by RQ2L84Q-ROW** [comment]
Well it seems not working... It was working at `localhost` I will check again.

**Comment by RQ2L84Q-ROW** [comment]
@yhakamay It is working indeed.
1. Chrome window
2. Chrome **private** window

Did you join from the same browser? Due to the permission configuration

`await auth.setPersistence(authInstance, auth.browserLocalPersistence);`

joining from the same browser might cause some problem.

Screen Shot 2021-09-23 at 11 33 39

**Comment by RQ2L84Q-ROW** [comment]
Please share your console log as well!

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW I've tried to join with two Google accounts, one on normal mode, another one on incognito mode. And it now works! Thanks for the suggestion.

**Review by yhakamay — APPROVED** [review]

**Pull request merged**
